=head1 The Next Generation of Sakai. A reference guide

=head2 Table Of Contents

=head3 Introduction ... Page 5

=over

=item The background to the next generation sakai.

=item So why not just re-engineer the sakai content management engine?

=item Enter JSR-170 (and JSR-283)

=item Why is this such a good thing?

=item Other intended benefits of the next generation sakai

=item Scalability

=item Easier and Quicker to use

=item Flexible, User Centered Structure

=item Offline friendly

=item User privacy and presence

=item Object focused permissions

=item Upgrade Pathway

=item Build quality

=item Better transaction management

=item Security

=item Flexible partitioning of users and administrative control

=back

=head3 Architecture Overview ... Page 8

=over

=item Apache Sling

=item Apache Jackrabbit

=item Everything is Content!

=item MySQL

=item Java Persistence API (JPA)

=item OSGi and Apache Felix

=item Bundles

=item Pax Web

=item Jetty

=item Apache HTTPd

=back

=head3 Building ... Page 10

=over

=item The build environment

=item Building Apache Dependencies

=item Apache Sling 5 incubator

=item Apache Felix web console 1.2.9-SNAPSHOT jar

=item Apache Shindig 1.0-incubating

=item Building sling

=item Building the next generation sakai

=back

=head3 Deploying ... Page 12

=over

=item Accessing the next generation sakai directly via built in jetty

=item Felix web management console

=item Startup switches for the next generation sakai

=item Load balancing behind apache httpd server

=back

=head3 Developing ... Page 14

=over

=item Using git

=item github

=item Forking

=item Following forks

=item Fetching other forks

=item git pre-commit hook

=item git on windows

=back

=head3 Content ... Page 16

=over

=item Sling Content and processing of content

=item Nodes

=item Rendering

=item Other renderers

=item Searching for an output renderer

=item Other methods

=item ESP Files - For the UI developer.

=item Other scripting languages

=item Servlets - For the Java developer

=item Searching content

=back

=head3 Authorization ... Page 18

=over

=item Building on Jackrabbit

=item Sling Authz Implementation Plan

=item Users and Groups Implementation

=item Authorizables

=item Users

=item Group

=item UserManager

=item Implementation

=item New Bundle for a ResourceProvider and Sling Post Operations for interacting with the jackrabbit UserManager

=item Jackrabbit 15/Sling UserManager Services

=item Extendable ACL Provider Implementation

=item JackRabbit / JSR283 Authz

=back

=head3 REST ... Page 20

=over

=item RESTful web services

=item REST web services provided by Sakai

=back

=head3 User and Group REST services ... Page 21

=over

=item User

=item Create User

=item Update User

=item Change Password

=item Delete User

=item Group

=item Create Group

=item Update Group

=item Delete Group

=back

=head3 Search REST services ... Page 25

=over

=item Search

=back

=head3 JSON ... Page 26

=head3 User Interface ... Page 27

=head3 Glossary ... Page 28

=head3 Credits ... Page 30

=head3 Licence ... Page 31

