=head1 Form based authentication

In addition to basic authentication, it is also possible to log in and out of
the next generation sakai via a form POST based mechanism. The servlet responds
at /system/sling/formlogin.

Methods

=over

=item POST

=back

Post Parameters

=over

=item sakaiauth:un The user name (required to log in)

=item sakaiauth:pw The user password (required to log in)

=item sakaiauth:login Set to 1 to log in

=item sakaiauth:logout Set to 1 to log out

=item Additional parameters become user node properties (optional)

=back

Response

=over

=item 200 user successfully authenticated.

=item 500 Failure. HTML explains failure.

=back

Examples

=over

=item Log in

 curl http://localhost:8080/system/sling/formlogin -Fsakaiauth:un=user -Fsakaiauth:pw=pass -Fsakaiauth:login=1
 
=item Log out

 curl http://localhost:8080/system/sling/formlogin -Fsakaiauth:logout=1
 
=back
