=head1 REST

=head2 RESTful web services

A RESTful web service is a simple web service implemented using HTTP and
Representational State Transfer (REST) principles
(http://en.wikipedia.org/wiki/Representational_State_Transfer). Such a web
service can be thought about as a collection of resources. The definition of
such a web service can be thought of as comprising three aspects:

=over

=item The URI for the web service such as http://example.com/physics/timetables

=item The MIME type of the data supported by the web service. In the next
generation sakai, this is typically JSON, but it could be XML, YAML, or in fact
pretty much anything.

=item The set of operations supported by the web service using HTTP methods
(e.g. POST, GET, PUT or DELETE).

=back

=head2 REST web services provided by Sakai

The next generation sakai harnesses the power of REST to deliver a flexible
user interface driven development model, where real user requirements dictate
functionality provision.

Furthermore, the exposure of functionality by this mechanism allows for more
realistic stress and functionality testing via automated means. Any language
with a suitable HTTP user agent can be used to supply the appropriate requests.
A set of perl libraries have been developed to support automated testing with
perl's LWP (search.cpan.org/perldoc?LWP) user agent. Currently, these scripts
and libraries can be found at:
https://saffron.caret.cam.ac.uk/svn/projects/sakoader/branches/improveGenericUse/Sling
