=head1 Search REST services

=head2 Search

Search through all JCR content repository nodes. The servlet registers with the
selector "query" and extension "json". That means it can be triggered by
accessing any repository node and appending ".query" to the node name and
".json" as the extension. The node called is irrelevant. The servlet always
queries the entire repository. All that is required is an existing resource.

Methods

=over

=item GET

=back

GET Parameters

=over

=item queryType The language for querying: "xpath" or "sql" (required)

=item statement The search statement in the language specified through the queryType parameter. (required)

=back

Response

=over

=item 200 Success, A JSON view of the search results is returned.

=item 500 Failure. HTML explains failure.

=back

Example

curl "http://localhost:8080/apps.query.json?queryType=xpath&statement=//*\[jcr:contains(.,\"test\")\]"
