=head1 User Interface

The latest version of the user interface can be fetched by doing:

$ svn co https://source.sakaiproject.org/svn/ux/branches/K2/trunk/uxportal/src/main/webapp/ dev

$ svn co https://source.sakaiproject.org/svn/ux/branches/K2/trunk/uxwidgets/src/main/webapp/ devwidgets

These folders contain static html, css, and js files and can be deployed simply
in to a web server. However, they rely on being able to communicate with the
next generation sakai via a set of well defined REST interfaces. As the system
is developed, these interfaces will become available and the process of
layering the new UI on top of the sakai system will be documented.
