=head1 Credits

In no particular order, the following people have contributed to this
documentation at various direct and indirect levels, such as providing
documentation on the sakai kernel google group that has been incorporated,
creating a build system for the docs, writing docs directly etc:

=over

=item Anthony Whyte

=item Carl Hall

=item Clay Fenlayson

=item Cris Holdorph

=item Daniel Parry (daniel@caret.cam.ac.uk)

=item David Horwitz

=item Ian Boston

=item John Norman

=item Laura James

=item Stuart Freeman

=item Tony Stevenson

=back
